# Generated by Django 6.0.3 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produto_estoque_remove_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.AddField(
            model_name='variacao',
            name='cor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
