# Generated by Django 6.0.3 on 2026-03-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_produto_cor_variacao_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('vestidos', 'Vestidos'), ('blusas', 'Blusas'), ('calcas', 'Calças'), ('conjuntos', 'Conjuntos'), ('saias', 'Saias'), ('shorts', 'Shorts'), ('jaquetas', 'Jaquetas')], default='', max_length=20),
        ),
    ]
